# Generated by Django 5.2.6 on 2025-09-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('grains', 'Grains'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('nuts_seeds', 'Nuts & Seeds'), ('spices', 'Spices'), ('beverages', 'Beverages'), ('sweets', 'Sweets'), ('oils', 'Oils')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('nutritional_info', models.JSONField(blank=True, default=dict)),
                ('vata_effect', models.CharField(choices=[('vata_+', 'Increases Vata'), ('vata_-', 'Decreases Vata'), ('pitta_+', 'Increases Pitta'), ('pitta_-', 'Decreases Pitta'), ('kapha_+', 'Increases Kapha'), ('kapha_-', 'Decreases Kapha'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('pitta_effect', models.CharField(choices=[('vata_+', 'Increases Vata'), ('vata_-', 'Decreases Vata'), ('pitta_+', 'Increases Pitta'), ('pitta_-', 'Decreases Pitta'), ('kapha_+', 'Increases Kapha'), ('kapha_-', 'Decreases Kapha'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('kapha_effect', models.CharField(choices=[('vata_+', 'Increases Vata'), ('vata_-', 'Decreases Vata'), ('pitta_+', 'Increases Pitta'), ('pitta_-', 'Decreases Pitta'), ('kapha_+', 'Increases Kapha'), ('kapha_-', 'Decreases Kapha'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('is_ayurvedic', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(max_length=255)),
                ('chart_type', models.CharField(choices=[('therapeutic', 'Therapeutic'), ('maintenance', 'Maintenance'), ('detox', 'Detox'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_charts', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosha_type', models.CharField(choices=[('vata', 'Vata'), ('pitta', 'Pitta'), ('kapha', 'Kapha'), ('vata-pitta', 'Vata-Pitta'), ('vata-kapha', 'Vata-Kapha'), ('pitta-kapha', 'Pitta-Kapha'), ('tridosha', 'Tridosha')], max_length=20)),
                ('recommendation_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_items', models.ManyToManyField(blank=True, to='diet_charts.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('mid_morning', 'Mid-Morning'), ('lunch', 'Lunch'), ('evening', 'Evening'), ('dinner', 'Dinner'), ('bedtime', 'Bedtime')], max_length=20)),
                ('meal_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timing', models.TimeField()),
                ('preparation_notes', models.TextField(blank=True)),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7')], default=1)),
                ('diet_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='diet_charts.dietchart')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_charts.fooditem')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='diet_charts.mealplan')),
            ],
        ),
    ]
