# Generated by Django 4.2.16 on 2025-09-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_name', models.CharField(max_length=255)),
                ('chart_type', models.CharField(choices=[('therapeutic', 'Therapeutic'), ('maintenance', 'Maintenance'), ('detox', 'Detox'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('pregnancy', 'Pregnancy'), ('diabetic', 'Diabetic'), ('hypertension', 'Hypertension'), ('digestive', 'Digestive Health'), ('immunity', 'Immunity Boosting')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('expected_outcomes', models.TextField(blank=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('based_on_diseases', models.ManyToManyField(blank=True, to='patients.diseaseanalysis')),
                ('based_on_prakriti', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.prakritianalysis')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_diet_charts', to='authentication.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_charts', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Diet Chart',
                'verbose_name_plural': 'Diet Charts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('grains', 'Grains'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('nuts_seeds', 'Nuts & Seeds'), ('spices', 'Spices'), ('beverages', 'Beverages'), ('sweets', 'Sweets'), ('oils', 'Oils'), ('legumes', 'Legumes'), ('herbs', 'Herbs'), ('meat', 'Meat & Fish')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('nutritional_info', models.JSONField(blank=True, default=dict)),
                ('vata_effect', models.CharField(choices=[('vata_+', 'Increases Vata'), ('vata_-', 'Decreases Vata'), ('pitta_+', 'Increases Pitta'), ('pitta_-', 'Decreases Pitta'), ('kapha_+', 'Increases Kapha'), ('kapha_-', 'Decreases Kapha'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('pitta_effect', models.CharField(choices=[('vata_+', 'Increases Vata'), ('vata_-', 'Decreases Vata'), ('pitta_+', 'Increases Pitta'), ('pitta_-', 'Decreases Pitta'), ('kapha_+', 'Increases Kapha'), ('kapha_-', 'Decreases Kapha'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('kapha_effect', models.CharField(choices=[('vata_+', 'Increases Vata'), ('vata_-', 'Decreases Vata'), ('pitta_+', 'Increases Pitta'), ('pitta_-', 'Decreases Pitta'), ('kapha_+', 'Increases Kapha'), ('kapha_-', 'Decreases Kapha'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('is_ayurvedic', models.BooleanField(default=True)),
                ('is_organic', models.BooleanField(default=False)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('all_season', 'All Season')], default='all_season', max_length=20)),
                ('preparation_methods', models.JSONField(blank=True, default=list)),
                ('contraindications', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('calories_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('mid_morning', 'Mid-Morning'), ('lunch', 'Lunch'), ('evening', 'Evening'), ('dinner', 'Dinner'), ('bedtime', 'Bedtime'), ('snack', 'Snack')], max_length=20)),
                ('meal_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timing', models.TimeField()),
                ('preparation_notes', models.TextField(blank=True)),
                ('cooking_time', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7')], default=1)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diet_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='diet_charts.dietchart')),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['day_of_week', 'timing'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_charts.fooditem')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='diet_charts.mealplan')),
            ],
            options={
                'verbose_name': 'Meal Item',
                'verbose_name_plural': 'Meal Items',
                'ordering': ['order', 'food_item__name'],
            },
        ),
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosha_type', models.CharField(choices=[('vata', 'Vata'), ('pitta', 'Pitta'), ('kapha', 'Kapha'), ('vata-pitta', 'Vata-Pitta'), ('vata-kapha', 'Vata-Kapha'), ('pitta-kapha', 'Pitta-Kapha'), ('tridosha', 'Tridosha')], max_length=20)),
                ('recommendation_type', models.CharField(choices=[('favorable_foods', 'Favorable Foods'), ('avoid_foods', 'Foods to Avoid'), ('lifestyle', 'Lifestyle Recommendations'), ('timing', 'Meal Timing'), ('preparation', 'Food Preparation'), ('general', 'General Guidelines')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('detailed_guidelines', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.doctorprofile')),
                ('food_items', models.ManyToManyField(blank=True, to='diet_charts.fooditem')),
            ],
            options={
                'verbose_name': 'Diet Recommendation',
                'verbose_name_plural': 'Diet Recommendations',
                'ordering': ['dosha_type', 'priority', 'title'],
            },
        ),
    ]
