# Generated by Django 4.2.24 on 2025-09-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_charts', '0001_initial'),
    ]

    operations = [
    ]
