# Generated by Django 4.2.24 on 2025-09-21 00:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_doctorprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet_charts', '0002_auto_20250921_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='food_items',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='meal_plan',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='diet_chart',
        ),
        migrations.RenameField(
            model_name='dietchart',
            old_name='is_active',
            new_name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='dietchart',
            name='based_on_diseases',
        ),
        migrations.RemoveField(
            model_name='dietchart',
            name='based_on_prakriti',
        ),
        migrations.RemoveField(
            model_name='dietchart',
            name='contraindications',
        ),
        migrations.RemoveField(
            model_name='dietchart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dietchart',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='dietchart',
            name='expected_outcomes',
        ),
        migrations.RemoveField(
            model_name='dietchart',
            name='progress_notes',
        ),
        migrations.RemoveField(
            model_name='dietchart',
            name='special_instructions',
        ),
        migrations.AddField(
            model_name='dietchart',
            name='daily_meals',
            field=models.JSONField(default=dict, help_text='The actual meal plan for each day'),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='disease_analysis',
            field=models.JSONField(blank=True, help_text='Snapshot of disease analysis', null=True),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='dosha_focus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Which doshas to focus on', size=None),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='food_restrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Dietary restrictions', size=None),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='generation_parameters',
            field=models.JSONField(blank=True, help_text='Parameters used for AI generation', null=True),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='meal_distribution',
            field=models.JSONField(blank=True, help_text='Percentage distribution of calories across meals', null=True),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='patient_preferences',
            field=models.JSONField(blank=True, help_text='Dietary preferences, allergies, etc.', null=True),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='prakriti_analysis',
            field=models.JSONField(blank=True, help_text='Snapshot of prakriti analysis', null=True),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='target_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='total_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='dietchart',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='chart_type',
            field=models.CharField(choices=[('7_day', '7 Day'), ('14_day', '14 Day'), ('30_day', '30 Day'), ('custom', 'Custom')], default='7_day', max_length=20),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_diet_charts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_charts', to='authentication.unifiedpatient'),
        ),
        migrations.AlterField(
            model_name='dietchart',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dietchart',
            constraint=models.CheckConstraint(check=models.Q(('total_days__gt', 0)), name='check_positive_days'),
        ),
        migrations.AddConstraint(
            model_name='dietchart',
            constraint=models.CheckConstraint(check=models.Q(('target_calories__isnull', True), ('target_calories__gt', 0), _connector='OR'), name='check_positive_calories'),
        ),
        migrations.AddConstraint(
            model_name='dietchart',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='check_date_order'),
        ),
        migrations.AlterModelTable(
            name='dietchart',
            table='diet_charts',
        ),
        migrations.DeleteModel(
            name='DietRecommendation',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='MealItem',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
