# Generated by Django 4.2.24 on 2025-09-20 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('serving_size', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber_g', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rasa', models.JSONField(default=list, help_text='Array of tastes (Sweet, Sour, Salty, Pungent, Bitter, Astringent)')),
                ('guna', models.JSONField(default=list, help_text='Array of qualities (Heavy, Light, Hot, Cold, Oily, Dry, etc.)')),
                ('virya', models.CharField(choices=[('Heating', 'Heating'), ('Cooling', 'Cooling'), ('Neutral', 'Neutral')], max_length=50)),
                ('vata_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral')], max_length=20)),
                ('pitta_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral')], max_length=20)),
                ('kapha_effect', models.CharField(choices=[('pacifies', 'Pacifies'), ('aggravates', 'Aggravates'), ('neutral', 'Neutral')], max_length=20)),
                ('meal_types', models.JSONField(default=list, help_text='Array of meal types')),
                ('food_category', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list, help_text='Array of dietary tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'db_table': 'food_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
