# Generated by Django 5.2.6 on 2025-09-19 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_consultation', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.doctorprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('symptoms', models.TextField()),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('diagnosis_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('initial', 'Initial Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Check-up')], max_length=20)),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='authentication.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrakritiAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_dosha', models.CharField(choices=[('vata', 'Vata'), ('pitta', 'Pitta'), ('kapha', 'Kapha'), ('vata-pitta', 'Vata-Pitta'), ('vata-kapha', 'Vata-Kapha'), ('pitta-kapha', 'Pitta-Kapha'), ('tridosha', 'Tridosha')], max_length=20)),
                ('secondary_dosha', models.CharField(blank=True, choices=[('vata', 'Vata'), ('pitta', 'Pitta'), ('kapha', 'Kapha'), ('vata-pitta', 'Vata-Pitta'), ('vata-kapha', 'Vata-Kapha'), ('pitta-kapha', 'Pitta-Kapha'), ('tridosha', 'Tridosha')], max_length=20)),
                ('vata_score', models.IntegerField(default=0)),
                ('pitta_score', models.IntegerField(default=0)),
                ('kapha_score', models.IntegerField(default=0)),
                ('analysis_notes', models.TextField(blank=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prakriti_analyses', to='patients.patient')),
            ],
        ),
    ]
