# Generated by Django 4.2.24 on 2025-09-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_doctorprofile_options_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False, 'ordering': ['-registration_date'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='authentication.unifiedprofile'),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='diagnosed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to='authentication.unifiedprofile'),
        ),
        migrations.AlterField(
            model_name='prakritianalysis',
            name='analyzed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prakriti_analyses', to='authentication.unifiedprofile'),
        ),
    ]
