# Generated by Django 4.2.24 on 2025-09-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_doctorprofile_options_and_more'),
        ('patients', '0002_alter_patient_options_alter_consultation_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='authentication.unifiedpatient'),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to='authentication.unifiedpatient'),
        ),
        migrations.AlterField(
            model_name='prakritianalysis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prakriti_analyses', to='authentication.unifiedpatient'),
        ),
    ]
