# Generated by Django 4.2.24 on 2025-09-20 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_consultation_patient_and_more'),
        ('authentication', '0002_alter_doctorprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrakritiAnalysis',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('primary_dosha', models.CharField(choices=[('vata', 'Vata'), ('pitta', 'Pitta'), ('kapha', 'Kapha'), ('vata-pitta', 'Vata-Pitta'), ('vata-kapha', 'Vata-Kapha'), ('pitta-kapha', 'Pitta-Kapha'), ('tridosha', 'Tridosha')], max_length=20)),
                ('secondary_dosha', models.CharField(blank=True, choices=[('vata', 'Vata'), ('pitta', 'Pitta'), ('kapha', 'Kapha'), ('vata-pitta', 'Vata-Pitta'), ('vata-kapha', 'Vata-Kapha'), ('pitta-kapha', 'Pitta-Kapha'), ('tridosha', 'Tridosha')], max_length=20)),
                ('vata_score', models.IntegerField(default=0)),
                ('pitta_score', models.IntegerField(default=0)),
                ('kapha_score', models.IntegerField(default=0)),
                ('analysis_notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prakriti_analyses', to='authentication.unifiedprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prakriti_analyses', to='authentication.unifiedpatient')),
            ],
            options={
                'verbose_name': 'Prakriti Analysis',
                'verbose_name_plural': 'Prakriti Analyses',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseAnalysis',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255)),
                ('icd_code', models.CharField(blank=True, max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('cured', 'Cured'), ('chronic', 'Chronic')], default='active', max_length=20)),
                ('symptoms', models.TextField()),
                ('diagnosis_notes', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('medications', models.JSONField(default=list)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('diagnosis_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('diagnosed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to='authentication.unifiedprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_analyses', to='authentication.unifiedpatient')),
            ],
            options={
                'verbose_name': 'Disease Analysis',
                'verbose_name_plural': 'Disease Analyses',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('consultation_type', models.CharField(choices=[('initial', 'Initial Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Check-up'), ('telemedicine', 'Telemedicine'), ('diet_review', 'Diet Chart Review')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('vital_signs', models.JSONField(default=dict)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('consultation_date', models.DateTimeField(auto_now_add=True)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='authentication.unifiedprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='authentication.unifiedpatient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-consultation_date'],
            },
        ),
    ]
