# Generated by Django 4.2.24 on 2025-09-20 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20250921_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='actual_duration',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='vital_signs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='follow_up_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diseaseanalysis',
            name='medications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='prakritianalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
