# Generated by Django 4.2.24 on 2025-09-21 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_alter_doctorprofile_options_and_more'),
        ('patients', '0005_remove_consultation_actual_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('blood-test', 'Blood Test'), ('urine-test', 'Urine Test'), ('xray', 'X-Ray'), ('mri', 'MRI Scan'), ('ct-scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('ecg', 'ECG'), ('consultation', 'Consultation Report'), ('prescription', 'Prescription'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('public_url', models.URLField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='authentication.unifiedpatient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Report',
                'verbose_name_plural': 'Patient Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_accessed', models.BooleanField(default=False)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='patients.patientreport')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Share',
                'verbose_name_plural': 'Report Shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='patients.patientreport')),
            ],
            options={
                'verbose_name': 'Report Comment',
                'verbose_name_plural': 'Report Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientreport',
            index=models.Index(fields=['patient', 'report_type'], name='patients_pa_patient_5cb1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientreport',
            index=models.Index(fields=['patient', 'created_at'], name='patients_pa_patient_1bb37d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientreport',
            index=models.Index(fields=['status', 'created_at'], name='patients_pa_status_1b8fe3_idx'),
        ),
    ]
